regions:
- eu-west-1
- global

account-blocklist:
- "999999999999" # production

accounts:
  "501015370583": # baracs
    filters:
      IAMUser:
      - "daily-admin"
      IAMRole:
      - "daily-admin-role"
      IAMPolicy:
      - "arn:aws:iam::501015370583:policy/daily-admin-policy"
      IAMVirtualMFADevice:
      - "arn:aws:iam::501015370583:mfa/daily-admin"
      IAMRolePolicyAttachment:
      - "daily-admin-role -> AdministratorAccess"
      IAMUserAccessKey:
      - "daily-admin -> AKIAXJJWX3NL67KXYVMK"